services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: nachitou
      POSTGRES_PASSWORD: clifford
      POSTGRES_DB: nachito
    ports:
      - "5432:5432"
    networks:
      - my_network

  redis:
    image: redis:7.0.5
    ports:
      - "6380:6380"
      
  servidor:
     build:
      context: ./
      dockerfile: ./servidor/Dockerfile
     ports:
      - "50051:50051"

  cliente:
    build:
      context: ./
      dockerfile: ./cliente/Dockerfile

networks:
  my_network:
    driver: bridge