
version: '3'

services:
  server:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - redis
      - postgres

  client:
    build: .
    depends_on:
      - server

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

networks:
  default:
    name: grpc-redis-network