# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cache_pb2 as protobufs_dot_cache__pb2


class CacheServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Pingpacientes = channel.unary_unary(
                '/CacheService/Pingpacientes',
                request_serializer=protobufs_dot_cache__pb2.EmptyMessage.SerializeToString,
                response_deserializer=protobufs_dot_cache__pb2.EmptyMessageresponse.FromString,
                )


class CacheServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Pingpacientes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Pingpacientes': grpc.unary_unary_rpc_method_handler(
                    servicer.Pingpacientes,
                    request_deserializer=protobufs_dot_cache__pb2.EmptyMessage.FromString,
                    response_serializer=protobufs_dot_cache__pb2.EmptyMessageresponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CacheService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Pingpacientes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CacheService/Pingpacientes',
            protobufs_dot_cache__pb2.EmptyMessage.SerializeToString,
            protobufs_dot_cache__pb2.EmptyMessageresponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
